# FROM mysql:5.7

# ENV MYSQL_DATABASE reviewAPI
# ENV MYSQL_ROOT_PASSWORD 123
# ENV MYSQL_USER root
# ENV MYSQL_PASSWORD 123
# ENV DATABASE_HOST db

# EXPOSE 3306

# COPY ./sql-scripts /docker-entrypoint-initdb.d/

